version: "3"

services:
  gotify:
    image: gotify/server:latest
    container_name: "gotify"
    restart: unless-stopped
    ports:
      - 8008:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS
    volumes:
      - "${GOTIFY_DATA_DIR:-.}/data:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.gotify-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.gotify-https.entrypoints: "https"
      traefik.http.routers.gotify-https.rule: "Host(`gotify.${DOMAIN}`)"
      traefik.http.routers.gotify-https.tls: "true"
      traefik.http.routers.gotify-https.tls.certresolver: "myresolver"
      traefik.http.routers.gotify.entrypoints: "http"
      traefik.http.routers.gotify.middlewares: "gotify-https-redirect"
      traefik.http.routers.gotify.rule: "Host(`gotify.${DOMAIN}`)"
