version: "3.9"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: "navidrome"
    restart: unless-stopped
    environment:
      ND_LOGLEVEL: debug
    ports:
      - "4533:4533"
    volumes:
      - ${NAVIDROME_DATA_DIR:-.}/data:/data
      - /mnt/music:/music:ro
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.navidrome-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.navidrome-https.entrypoints: "https"
      traefik.http.routers.navidrome-https.rule: "Host(`navidrome.${DOMAIN}`)"
      traefik.http.routers.navidrome-https.tls: "true"
      traefik.http.routers.navidrome-https.tls.certresolver: "myresolver"
      traefik.http.routers.navidrome.entrypoints: "http"
      traefik.http.routers.navidrome.middlewares: "navidrome-https-redirect"
      traefik.http.routers.navidrome.rule: "Host(`navidrome.${DOMAIN}`)"
      # watchtower enabled
      com.centurylinklabs.watchtower.enable: "true"

