version: "3.9"
services:

  dndtools:
    build:
      context: ${DNDTOOLS_DIR:-.}/dockerfiles
    image: dndtools:latest
    container_name: "dndtools"
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ${DNDTOOLS_DIR:-.}/dndtools-source:/app
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.dndtools-https-redirect.redirectscheme.scheme: "https"
      #traefik.http.middlewares.dndtools-auth.basicauth.users: "${ADMIN}"
      traefik.http.routers.dndtools-https.entrypoints: "https"
      traefik.http.routers.dndtools-https.rule: "Host(`dndtools.${DOMAIN}`)"
      traefik.http.routers.dndtools-https.tls: "true"
      traefik.http.routers.dndtools-https.tls.certresolver: "myresolver"
      #traefik.http.routers.dndtools-https.middlewares: "dndtools-auth"
      traefik.http.routers.dndtools.entrypoints: "http"
      traefik.http.routers.dndtools.middlewares: "dndtools-https-redirect"
      traefik.http.routers.dndtools.rule: "Host(`dndtools.${DOMAIN}`)"
