version: "3.9"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: "uptime_kuma"
    ports:
      - "3001:3001"
    volumes:
      - ${UPTIME_DATA_DIR:-.}/data:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.uptime-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.uptime-https.entrypoints: "https"
      traefik.http.routers.uptime-https.rule: "Host(`status.${DOMAIN}`)"
      traefik.http.routers.uptime-https.tls: "true"
      traefik.http.routers.uptime-https.tls.certresolver: "myresolver"
      traefik.http.routers.uptime.entrypoints: "http"
      traefik.http.routers.uptime.middlewares: "uptime-https-redirect"
      traefik.http.routers.uptime.rule: "Host(`status.${DOMAIN}`)"
      # watchtower enabled
      com.centurylinklabs.watchtower.enable: "true"


