version: "3.9"
services:
    tiddlywiki_dndwiki:
        build:
            context: ${TIDDLYWIKI_DIR:-.}
            dockerfile: dockerfile.dndwiki
        # env vars seem to make node/tiddlywiki behave weirdly depending on what file they're in
        environment:
            - TW_WIKINAME=dndwiki
            - TW_PORT=8080
            - TW_RENDERTYPE="text/plain"
        ports:
            - 8180:8080
        volumes:
            - /mnt/temp_dataset/wikis:/app
        labels:
            traefik.enable: "true"
            traefik.http.middlewares.dndwiki-https-redirect.redirectscheme.scheme: "https"
            traefik.http.middlewares.dndwiki-auth.basicauth.users: "${WIKI_ADMIN}"
            traefik.http.routers.dndwiki-https.entrypoints: "https"
            traefik.http.routers.dndwiki-https.rule: "Host(`dndwiki.${DOMAIN}`)"
            traefik.http.routers.dndwiki-https.tls: "true"
            traefik.http.routers.dndwiki-https.tls.certresolver: "myresolver"
            traefik.http.routers.dndwiki-https.middlewares: "dndwiki-auth"
            traefik.http.routers.dndwiki.entrypoints: "http"
            traefik.http.routers.dndwiki.middlewares: "dndwiki-https-redirect"
            traefik.http.routers.dndwiki.rule: "Host(`dndwiki.${DOMAIN}`)"


