FROM node:16-alpine

RUN apk add dos2unix

RUN npm install -g tiddlywiki

ENV TW_ROOTTIDDLER="$:/core/save/all" \
    TW_SERVETYPE="text/html" \
    TW_USERNAME="anonymous" \
    TW_PASSWORD="" \
    TW_HOST="0.0.0.0" \
    TW_PATHPREFIX=""

WORKDIR /app

COPY init-and-run /usr/local/bin/init-and-run
RUN dos2unix /usr/local/bin/init-and-run

#USER node
CMD ["/bin/sh","/usr/local/bin/init-and-run"]
